#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\IndexController::index

newarticle:
  path: /newarticle
  controller: App\Controller\NewArticleController::newArticleForm

article_show:
  path: /article/{id}
  controller: App\Controller\IndexController::show

snake:
  path: /snake
  controller: App\Controller\SnakeController::index
